config/routes.rb
=begin
  specification
  name = application routing
  function = routingを定義する。
  note = bundle exc rails db:seedでトリガー。
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 行先URL
  output = 行先controler
  end of specification
=end

Rails.application.routes.draw do
  get 'satistics/index'

  root 'orders#index'

  #???
  get 'orders/index', as:'orders'
  get 'orders/index'
  get '/orders/complete'
  post '/orders/complete'
  get '/orders/complete_index'
  get '/satistics/index', as:'satistics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
=begin
  specification
  name = オリジンのmodel
  function = 全てのmodelの継承元。
  note = 全てのモデルはApplicationRecordを継承。
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = none
  output = none
  end of specification
=end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order_status.rb
=begin
  specification
  name = 注文状況のmodel
  function = 注文状況を動的に保存。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 取得したいデータのパラメータ。
  output = 注文情報に関するオブジェクト。
  end of specification
=end

class OrderStatus < ApplicationRecord
  belongs_to :product
  belongs_to :table_number

  #合計金額を計算
  def self.total
    target = OrderStatus.where(order_status:'true')
    unless target.nil?
    total = 0
    target.each do |t|
      total += t.product.price * t.amount
    end
      total
    end
  end
  #モデルの中から検索対象にヒットするものを検索する。
  def self.search(key)
    OrderStatus.joins(:product).includes(:product).where(order_status:'true').where(['products.name LIKE ?', "%#{key}%"])
  end

end

app/models/product.rb
=begin
  specification
  name = 商品情報の入ったmodel
  function = 商品の情報を静的に保存。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 取得したいデータのパラメータ。
  output = 商品に関するオブジェクト。
  end of specification
=end

class Product < ApplicationRecord
  #多対一のリレーションを定義
  has_many :order_statuses, dependent: :destroy
end

app/models/table_number.rb
=begin
  specification
  name = テーブル番号のmodel
  function = テーブル情報を静的に保存。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 取得したいデータのパラメータ。
  output = テーブル番号に関するオブジェクト。
  end of specification
=end

class TableNumber < ApplicationRecord
  #多対一のリレーションを定義
  has_many :order_statuses, dependent: :destroy
end

app/controllers/application_controller.rb
=begin
  specification
  name = オリジンのcontroler
  function = 全てのcontrolerはApplicationControllerを継承。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = none
  output = none
  end of specification
=end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
=begin
  specification
  name = 注文状況のcontroler
  function = 注文管理全般を担う。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 取得したいデータのパラメータ。
  output = 注文情報に関するオブジェクトを生成しViewを呼び出す。
  end of specification
=end

class OrdersController < ApplicationController
  #インデックス画面の表示
  def index
    @order = OrderStatus.where(order_status:'false').page(params[:page])
    @order_status = OrderStatus.new
  end

  def complete
    ids = []
    if params[:order_status].blank?
      redirect_to root_path and return
    else
    #完了する注文のパラメータを取得
    ids = params[:order_status][:id]
    end
    @order_comp = OrderStatus.where(id:ids)
    @order_comp.update_all({ :order_status => 'true' })
    redirect_to root_path,notice:"#{ids.length}個の注文を完了しました。"
  end
#完了済み注文画面の表示
  def complete_index
    @order = OrderStatus.where(order_status:'true').page(params[:page])
  end

  private
  def order_params
    params.require(:order_status).permit(:id)
  end
end

app/controllers/satistics_controller.rb
=begin
  specification
  name = 注文統計のcontroler
  function = 注文統計全般を担う。
  note = none
  date = 2017/6/20
  author = Yuto Suzuki
  History = V1.00/V1.00
  input = 取得したいデータのパラメータ。
  output = 注文管理に関するオブジェクトを生成しViewを呼び出す。
  end of specification
=end

class SatisticsController < ApplicationController
  #VALID_SORT_COLUMNSに含まれないパラメータは取得できない。
  VALID_SORT_COLUMNS = %w(products.name amount products.price products.category table_numbers.table_number)
  def index
    @satistics = OrderStatus.where(order_status:'true').page(params[:page])
    #以下ソート処理
    sort = params[:sort] if VALID_SORT_COLUMNS.include?(params[:sort])
  unless sort.nil?
    if sort == 'amount'
      @satistics = OrderStatus.where(order_status:'true').order("#{sort} DESC").page(params[:page])
    elsif sort == 'table_numbers.table_number'
      @satistics = OrderStatus.joins(:table_number).includes(:table_number).where(order_status:'true').order("#{sort} DESC").page(params[:page])
    elsif sort == 'products.price' || sort == 'products.category'
      @satistics = OrderStatus.joins(:product).includes(:product).where(order_status:'true').order("#{sort} DESC").page(params[:page])
    elsif sort == 'products.name'
      @satistics = OrderStatus.joins(:product).includes(:product).where(order_status:'true').order("#{sort} DESC").page(params[:page])
    end
  end

  #以下検索処理
  unless params[:search].blank?
    logger.debug params[:search]
    @satistics = OrderStatus.search(params[:search]).page(params[:page])
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/satistics_helper.rb
module SatisticsHelper
end

app/views/layouts/application.html.erb
<!--<%=#
  #specification
  #name = オリジンスタイルシート
  #function = 全てのViewの大枠を決める。
  #note = 特になし。
  #date = 2017/6/20
  #author = Yuto Suzuki
  #History = V1.00/V1.00
  #input = none
  #output = View file
  #end of specification
%>-->
<!DOCTYPE html>
<html>
  <head>
    <title>FCS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--yield部分が各種Viewを投影-->
    <%= yield %>
  </body>
</html>

app/views/orders/complete.html.erb
<h1>Orders#complete</h1>
<p>Find me in app/views/orders/complete.html.erb</p>

app/views/orders/complete_index.html.erb
<!--<%=#
  #specification
  #name = 注文完了画面
  #function = 注文完了画面のViewを生成
  #note = 特になし。
  #date = 2017/6/20
  #author = Yuto Suzuki
  #History = V1.00/V1.00
  #input = none
  #output = View file
  #end of specification
%>-->
<div id = "main">
<div id="order_index">
  <div id = 'day_zone'><i><%= Date.today%></i></div>
  <!--eachメソッドが取得したオブジェクトを一つずつ分解-->
<% @order.each do |order|%>
<div id = "orders">
<table class = "table table-bordered">
<tbody>
  <tr>
    <td colspan="2">テーブル番号:</td>
  </tr>
  <tr>
    <td>
      商品名：<%= order.product.name%>
    </td>
    <td>
      数量：<%= order.amount%>
    </td>
  </tr>
  <tr>
    <th colspan="3">備考</th>
  </tr>
  <tr>
    <td colspan="3"><%= order.product.option%></td>
</th>
  </tr>
  </tbody>
</table>
</div>
<%end%>
<div class="switch"><%= button_to "注文一覧へ戻る", {action: :index}, {method: :get}%></div>
<div class = "page_nate_area"><%= paginate @order %></div>
</div>
</div>

app/views/orders/index.html.erb
<!--<%=#
  #specification
  #name = 注文画面index
  #function = 到着した注文を順次表示する。
  #note = 特になし。
  #date = 2017/6/20
  #author = Yuto Suzuki
  #History = V1.00/V1.00
  #input = none
  #output = View file
  #end of specification
%>-->

<div id = "main">
<div id = "order_index">
  <%unless flash.blank?%>
  <p><%= flash[:notice]%></p>
  <%end%>
  <div id = 'day_zone'><i><%= Date.today%></i>
    <%= button_to "閉店時切替",{controller:'satistics',action:'index'},{method: :get}%>
  </div>
  <%= form_for @order_status, :url => {:action => 'complete'} do |f|%>
  <div id="contents">
    <% if @order.blank?%>
    <span>まだ注文がありません!!</sapn>
    <% else%>
  <% @order.each do |order|%>
  <div id = "orders">
  <table class = "table table-bordered">
  <tbody>
    <tr>
      <td rowspan="2" style="padding-top:30px;"><%= f.check_box 'id', {multiple: true}, order.id, false %></td>
      <td colspan="2">テーブル番号:<b><%= order.table_number.table_number%></b></td>
    </tr>
    <tr>
      <td>
        商品名：<b><%= order.product.name%></b>
      </td>
      <td>
        数量：<b><%= order.amount%></b>
      </td>
    </tr>
    <tr>
      <th colspan="3">備考</th>
    </tr>
    <tr>
      <td colspan="3"><%= order.product.option%></td>
  </th>
    </tr>
    </tbody>
  </table>
  </div>
  <%end%>
  <%end%>
</div>
  <div class = "form_area"><%= f.button "チェックしたものを完了する。"%></div>
<%end%>
<%= button_to "完了済み一覧を表示する。",{action:'complete_index'},{method: :get}%>
<div class = "page_nate_area"><%= paginate @order %></div>
</div>
<!--end of order_index-->
</div>
<!--end of main-->

app/views/satistics/index.html.erb
<!--<%=#
  #specification
  #name = 統計index
  #function = 閉店時の統計画面のViewを出力
  #note = 特になし。
  #date = 2017/6/20
  #author = Yuto Suzuki
  #History = V1.00/V1.00
  #input = none
  #output = View file
  #end of specification
%>-->

<div id="main">
  <div id="satistics">
    <div id = 'day_zone'><i><%= Date.today%></i>
      <%= button_to "閉店時切替",{controller:'orders',action:'index'},{method: :get}%>
    </div>
    <%= form_tag satistics_path, {:method => 'get'} do%>
    <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
    <%end%>
    <div id="orders">
    <table class="table table-bordered">
      <tr>
        <th><%= link_to "商品名", sort: "products.name" %></th>
        <th><%= link_to "注文数", sort: "amount" %></th>
        <th><%= link_to "単価", sort: "products.price" %></th>
        <th><%= link_to "テーブル番号", sort: "table_numbers.table_number" %></th>
        <th><%= link_to "カテゴリ", sort: "products.category" %></th>
      </tr>
      <% @satistics.each do |s| %>
      <tr>
        <td><%=s.product.name%></td>
        <td><%=s.amount%></td>
        <td><%=s.product.price%></td>
        <td><%=s.table_number.table_number%></td>
        <td><%=s.product.category%></td>
      </tr>
      <% end %>
      <tr>
          <td><div class = "page_nate_area"><%= paginate @satistics %></div></td>
          <td colspan="4" style="text-align:right;font-size:30px;">
            <b>売り上げ総計　<%= OrderStatus.total%>円</b>
          </td>
      </tr>
    </table>

  </div>
  <!--end of orders-->
  </div>
  <!--end of satistics-->
</div>
<!--end of main-->